// Mock data for testing the application
export const MOCK_APPLICATIONS = [
  {
    id: '1',
    firstName: 'Sarah',
    lastName: 'Johnson',
    email: 'sarah.johnson@school.edu',
    phone: '555-0101',
    currentSchool: 'Lincoln Elementary School',
    yearsExperience: '8',
    currentCertification: 'Elementary Education',
    desiredAccreditation: 'Advanced Mathematics Specialist',
    education: "Bachelor's in Elementary Education, Master's in Mathematics Education",
    additionalCertifications: 'National Board Certification, STEM Education Certificate',
    teachingPhilosophy: 'I believe in fostering a growth mindset and making mathematics accessible to all students through hands-on learning experiences.',
    documents: [],
    status: 'pending',
    submittedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    comments: [
      {
        id: 'c1',
        text: 'Strong credentials. Need to review teaching portfolio.',
        createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        author: 'Admin',
      },
    ],
  },
  {
    id: '2',
    firstName: 'Michael',
    lastName: 'Chen',
    email: 'michael.chen@highschool.edu',
    phone: '555-0102',
    currentSchool: 'Washington High School',
    yearsExperience: '12',
    currentCertification: 'Secondary Science Education',
    desiredAccreditation: 'Advanced Science Research Mentor',
    education: "Bachelor's in Biology, Master's in Science Education, PhD in Educational Leadership",
    additionalCertifications: 'Advanced Placement Biology Certified, Science Olympiad Coach',
    teachingPhilosophy: 'Encouraging scientific inquiry and critical thinking through real-world problem solving and research opportunities.',
    documents: [],
    status: 'approved',
    submittedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    approvedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    comments: [
      {
        id: 'c2',
        text: 'Excellent qualifications and experience.',
        createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        author: 'Admin',
      },
      {
        id: 'c3',
        text: 'Approved for Advanced Science Research Mentor accreditation.',
        createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        author: 'Admin',
      },
    ],
  },
  {
    id: '3',
    firstName: 'Emily',
    lastName: 'Rodriguez',
    email: 'emily.rodriguez@school.edu',
    phone: '555-0103',
    currentSchool: 'Roosevelt Middle School',
    yearsExperience: '6',
    currentCertification: 'English Language Arts',
    desiredAccreditation: 'Literacy Specialist',
    education: "Bachelor's in English Literature, Master's in Literacy Education",
    additionalCertifications: 'Reading Recovery Trained, ESL Endorsement',
    teachingPhilosophy: 'Promoting literacy through culturally responsive teaching and differentiated instruction.',
    documents: [],
    status: 'pending',
    submittedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    comments: [],
  },
  {
    id: '4',
    firstName: 'David',
    lastName: 'Thompson',
    email: 'david.thompson@academy.edu',
    phone: '555-0104',
    currentSchool: 'Jefferson Academy',
    yearsExperience: '4',
    currentCertification: 'Physical Education',
    desiredAccreditation: 'Adapted Physical Education Specialist',
    education: "Bachelor's in Physical Education, pursuing Master's in Adapted PE",
    additionalCertifications: 'CPR/First Aid Certified, Youth Sports Coaching Certificate',
    teachingPhilosophy: 'Creating inclusive physical education environments where all students can succeed.',
    documents: [],
    status: 'rejected',
    submittedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    rejectedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    comments: [
      {
        id: 'c4',
        text: "Master's degree not yet completed. Please reapply after graduation.",
        createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        author: 'Admin',
      },
    ],
  },
  {
    id: '5',
    firstName: 'Jennifer',
    lastName: 'Williams',
    email: 'jennifer.williams@charter.edu',
    phone: '555-0105',
    currentSchool: 'Harmony Charter School',
    yearsExperience: '10',
    currentCertification: 'Special Education',
    desiredAccreditation: 'Autism Spectrum Disorder Specialist',
    education: "Bachelor's in Special Education, Master's in Autism Studies",
    additionalCertifications: 'Board Certified Behavior Analyst (BCBA), Assistive Technology Specialist',
    teachingPhilosophy: 'Leveraging evidence-based practices to support students with autism in reaching their full potential.',
    documents: [],
    status: 'pending',
    submittedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    comments: [],
  },
  {
    id: '6',
    firstName: 'Robert',
    lastName: 'Martinez',
    email: 'robert.martinez@district.edu',
    phone: '555-0106',
    currentSchool: 'Central High School',
    yearsExperience: '15',
    currentCertification: 'Social Studies',
    desiredAccreditation: 'Advanced Placement History Instructor',
    education: "Bachelor's in History, Master's in Education, ABD in History PhD",
    additionalCertifications: 'AP World History Certified, National History Day Judge',
    teachingPhilosophy: 'Making history relevant through primary source analysis and connection to current events.',
    documents: [],
    status: 'approved',
    submittedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    approvedAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    comments: [
      {
        id: 'c5',
        text: 'Outstanding qualifications. Approved.',
        createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
        author: 'Admin',
      },
    ],
  },
  {
    id: '7',
    firstName: 'Amanda',
    lastName: 'Taylor',
    email: 'amanda.taylor@elementary.edu',
    phone: '555-0107',
    currentSchool: 'Oakwood Elementary',
    yearsExperience: '7',
    currentCertification: 'Music Education',
    desiredAccreditation: 'Performing Arts Department Chair',
    education: "Bachelor's in Music Performance, Master's in Music Education",
    additionalCertifications: 'Orff Schulwerk Level III, Kodály Certification',
    teachingPhilosophy: 'Nurturing musical creativity and expression through performance and composition.',
    documents: [],
    status: 'pending',
    submittedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    comments: [
      {
        id: 'c6',
        text: 'Under review. Waiting for leadership experience documentation.',
        createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        author: 'Admin',
      },
    ],
  },
];

// Initialize storage with mock data
export const initializeMockData = () => {
  const existingData = localStorage.getItem('teacher_applications');
  if (!existingData || JSON.parse(existingData).length === 0) {
    localStorage.setItem('teacher_applications', JSON.stringify(MOCK_APPLICATIONS));
    return true;
  }
  return false;
};
